apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-state" (include "signet.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "signet.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
